print("Welcome to band name generator.")
city = input("What's the name of the city you grew up in?\n->")
pet = input("What's your pet's name?\n->")
bandName=str.capitalize(city) + " " + str.capitalize(pet)
print("Your band name could be " + bandName)